# -*- coding: utf-8 -*-

# ОКЭД (экон деятельность ) и дата создания добавить


"""Copy of telegram_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdb1a_Z8F21jdeTXTAix9t3sY7d9A37N
"""

# prompt: pytelegrambotapi

import telebot
import threading
import time
import requests
import pandas as pd
import numpy as np
from tqdm import tqdm
from telebot.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton

bin_url_1 = "https://api.adata.kz/api/company/"
bin_url_2 = "/ZVloUOB6nHzxcHfs4jPJEW12V2YxEgY?iinBin="
token_url = "https://api.adata.kz/api/company/info/check/ZVloUOB6nHzxcHfs4jPJEW12V2YxEgY?token="

modules = ['basic', 'status', 'riskfactor', 'trustworthy-extended']


def get_company_info(bin, module):
    bin_url = bin_url_1 + module + bin_url_2
    url = f"{bin_url}{bin}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        token_id = data['token']
        url_2 = f"{token_url}{token_id}"
        response_2 = requests.get(url_2)
        while response_2.json()['message'] == 'wait':
            time.sleep(1)
            response_2 = requests.get(url_2)

        if response_2.status_code == 200 and response_2.json()['message'] == 'ready':
            company_info = response_2.json()
            return company_info
        else:
            return {}

API_KEY = "7527203334:AAHUe5_O_9ZBHN88rkv3bAQmq9Qh28KWdHI"
bot = telebot.TeleBot(API_KEY)

user_state = {}

allowed_users = {
    7932774397: "Аруна",
    528517673: "Ескатов Алишер Маратович",
    1115327907: "Сафонов Александр",
    1090349915: "Баймурзинов Рустем Муратович",
    1106476172: "Абдиров Бекбулат Кайратович",
    435397805: "Глазырин Вячеслав Александрович",
    7852053436: "Коржов Дмитрий Александрович",
    752841282: "Шадрин Виталий Вячеславович",
    549557630: "Есентаев Дамир ",
    992265183: "Балгожа Рауан Еркебуланулы",
    1070083923: "Шубин Глеб Владимирович",
    1236379606: "Гугневич Евгений Павлович",
    1601907399: "Нургалиев Еламан",
    527670595: "Садовский Игорь Вальревич",
    7507209038: "Паршутин Евгений Игоревич",
    1787060581: "Вахнина Виктория Анатольевна",
    5087650386: "Кулбулдин Бауыржан",
    368200758: "Жунусов Айдын Бекович",
    6568553601: "Усенов Асанали Асхатович",
    7306728048: "Перешивкин Игорь",
    5970079059: "Шпаковский Сергей",
    717489456: "Шаткенов Арлан Нурдаулетович",
    5442237913: "Солдатенков Артем Викторович",
    543024941: "Жакиенов Данияр Берикович",
    477248141: "Анишкевич Владислав Сергеевич",
    780568746: "Терещенко Александр Григорьевич",
    2020413343: "Нургалиев Данияр Рамазанович",
    5303738892: "Койгелды Женис Даулетулы",
    508256083: "Яковлев Александр Александрович",
    8107067331: "Байгазиев Александр",
    1016809072: "Адомайтис Евгений",
    1897623417: "Лубянецкий Алексей Петрович",
    875411607: "Карташов Олег Валерьевич",
    1981124911: "Шульц Николай Викторович",
    6231136971: "Амирбек Жанибек Адильбекович",
    5176965194: "Кализатов Бауыржан Канатович",
    828188265: "Калиев Жанибек",
    782238817: "Сидоренко Алексей Александрович",
    7248286025: "Бородич Николай Михайлович",
    8088143874: "Авижич Виктор Викторович",
    436769994: "Максимов Станислав Валерьевич",
    230004989: "Кадырбек Куат",
    473547152: "Таукин Канат Аблаевич",
    516180924: "Ибраев Акежан Аулиханович",
    5679662661: "Соловьев Евгений Александрович",
    353184443: "Куташов Виталий",
    6110113341: "Тургумбаев Ильяс",
    715691300: "Турежанов Булат Агибаевич",
    1633629108: "Мади Назарбек",
    1372719987: "Джиоев Георгий",
    7022099012: "Сейдыков Максим Евгеньевич",
    7731034003: "Куаныш Мамбетов",
    592052143: "Герасимов Виталий Валерьевич",
    5672873644: "Жанат Охатов",
    170233096: "Наталья",
    7260153078: "Нурсултан",
    712766177: "Мурат",
    6263090827: "Кабимулдин Руфат Асетович",
    2096887718: "Ключка Сергей Сергеевич",
    6425627696: "Джексенбаев Ринат Каденович",
    5536766070: "Клиновицкий Андрей Александрович ",
    803315196: "Рак Егор Валерьевич",
    357140691: "Сериков Бахтияр",
    591725711: "Дауленов Азамат Айтжанович",
    5003150190: "Садвокасов Рустам",
    7687709758: "Жайырбаев Даурен Беимбекович",
    1101041371: "Яцынович Константин Юрьевич",
    892390481: "Бойко Олег",
    5086276503: "Асет Мукушев",
    7017920749: "Динара Айдарова",
    885253145: "Нуртуган"
}

@bot.message_handler(commands=['start'])
def start(message):
    # Проверяем, разрешён ли пользователь
    if message.chat.id not in allowed_users:
        bot.send_message(message.chat.id, "Извините, у вас нет доступа к этому боту.")
        return
    # Приветствуем пользователя по имени
    user_name = allowed_users[message.chat.id]
    markup = ReplyKeyboardMarkup(resize_keyboard=True)
    markup.add(KeyboardButton("🔍 Проверить компанию"))
    markup.add(KeyboardButton("ℹ️ Помощь"))

    bot.send_message(message.chat.id, f"Добро пожаловать, {user_name}! Выберите действие:", reply_markup=markup)
    user_state[message.chat.id] = "waiting_for_action"

# Handle Button Clicks
@bot.message_handler(func=lambda message: message.text in ["🔍 Проверить компанию", "ℹ️ Помощь"])
def handle_menu(message):
    if message.chat.id not in allowed_users:
        bot.send_message(message.chat.id, "Извините, у вас нет доступа к этому боту.")
        return
    if message.text == "🔍 Проверить компанию":
        bot.send_message(message.chat.id, "Пришлите БИН компании.")
        user_state[message.chat.id] = "waiting_for_id"
    elif message.text == "ℹ️ Помощь":
        bot.send_message(message.chat.id, "Этот бот помогает проверять компании по БИН. Просто отправьте БИН компании.")



# Handle Company ID Input
@bot.message_handler(func=lambda message: user_state.get(message.chat.id) == "waiting_for_id")
def handle_company_id(message):
    if message.chat.id not in allowed_users:
        bot.send_message(message.chat.id, "Извините, у вас нет доступа к этому боту.")
        return
    
    bot.send_message(message.chat.id, "Пожалуйста, подождите, запрос обрабатывается. Это может занять некоторое время.")
    
    company_id = message.text.strip()
    info = []

    basic = get_company_info(company_id, modules[0])['data']
    status = get_company_info(company_id, modules[1])['data']
    riskfactor = get_company_info(company_id, modules[2])['data']
    trustworthy_extended = get_company_info(company_id, modules[3])['data']

    if (get_company_info(company_id, modules[0])) != {}:

      if (status['company_status']) == False:
        info.append("❗ В списке «Бездействующее предприятие»")
      if (status['bankcrupt']) == True:
        info.append("❗ В списке «Банкрот»")

      if (riskfactor['company']['seized_bank_account']) == True:
        info.append("❗ Арест на банковские счета")
      if (riskfactor['company']['seized_property']) == True:
        info.append("❗ Арест на имущество")
      if (riskfactor['company']['ban_registration_actions_legal_ent']) == True:
        info.append("❗ Запрет на регистрационные действия ЮЛ")
      if (riskfactor['company']['ban_registration_actions_physical_ent']) == True:
        info.append("❗ Запрет на регистрационные действия ФЛ")
      if (riskfactor['company']['ban_notarius_actions']) == True:
        info.append("❗ Запрет на совершение нотариальных действия")

      if (riskfactor['head']['enforcement_debt']) == True:
        info.append("❗ Должник по исполнительным производствам")
      if (riskfactor['head']['debtor_for_executive_documents']) == True:
        info.append("❗ В списке должников по исполнительным документам")

      if (trustworthy_extended['tax_arrears_150']) == True:
        info.append("❗ В списке налогоплательщиков, имеющих налоговую задолженность более 150 МРП")
      if (trustworthy_extended['restriction_on_leaving']) == True:
        info.append("❗ Временное ограничение на выезд из РК")
      if (trustworthy_extended['transport_arrest']) == True:
        info.append("❗ В списке налогоплательщиков, имеющих налоговую задолженность более 150 МРП")
    else:
      info.append('Пожалуйста, предоставьте мне действительный БИН или ИИН')



    if info == []:
      bot.send_message(message.chat.id,'Полное наименование компании: ' + basic['name_ru'])
      bot.send_message(message.chat.id,'Юридический адрес: ' + basic['legal_address'])
      bot.send_message(message.chat.id,'ФИО руководителя: ' + basic['fullname_director'])
      bot.send_message(message.chat.id, "Проблем нет ✅")
    else:
      bot.send_message(message.chat.id,'Полное наименование компании: ' + basic['name_ru'])
      bot.send_message(message.chat.id,'Юридический адрес: ' + basic['legal_address'])
      bot.send_message(message.chat.id,'ФИО руководителя: ' + basic['fullname_director'])
      for i in info:
        bot.send_message(message.chat.id, i)

    # Add inline button to check another company
    markup = InlineKeyboardMarkup()
    markup.add(InlineKeyboardButton("🔄 Проверить другую компанию", callback_data="check_another"))
    bot.send_message(message.chat.id, "Хотите проверить другую компанию?", reply_markup=markup)

    user_state[message.chat.id] = "waiting_for_action"

# Handle Inline Button Click
@bot.callback_query_handler(func=lambda call: call.data == "check_another")
def check_another(call):
    if call.message.chat.id not in allowed_users:
        bot.send_message(call.message.chat.id, "Извините, у вас нет доступа к этому боту.")
        return
    bot.send_message(call.message.chat.id, "Пришлите БИН компании.")
    user_state[call.message.chat.id] = "waiting_for_id"

# Polling
def polling():
    bot.polling(non_stop=True, interval=0)

thread = threading.Thread(target=polling)
thread.start()
